name: auto-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCP Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Setting .env
        run: |
          echo "REACT_APP_SIGNUP_URL=${{ secrets.REACT_APP_SIGNUP_URL }}" >> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/referlink:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ../home/
            docker login -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }} ${{ secrets.NCP_CONTAINER_REGISTRY }}
            docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/referlink:latest
            docker stop referlink-front || true
            docker rm referlink-front || true
            docker run -d --restart unless-stopped -p 80:80 --name referlink-front ${{ secrets.NCP_CONTAINER_REGISTRY }}/referlink:latest
